### ISSUE TITLE
add support for specifying arbitrary beancount options

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/ledger2beancount#100]
It looks like (by personal experimentation) Beancount `option` directives have to be specified in the main Beancount file and cannot go in included file, similarly to what happens for `plugin` directives. Hence, to allow users to specify Beancount options, we need an `options` entry in ledger2beancount conffile, equivalent of the `plugins` entry we already have.

Real-life use case: adding a set of `document` options to the generated Beancount file, to cross-reference document from directories.

**Comment by zacchiro** [comment]
the syntax of the needed configuration entry is not evident though, as options are key-value pairs, but the same key can appear multiple times, e.g.:
```
option "documents" "documents/2018"
option "documents" "documents/2017"
option "documents" "documents/2016"
```

**Comment by tbm** [comment]
Maybe we should just read an (optional) file and include that?  Then you could define your headers somewhere and ledger2beancount adds it.

**Comment by zacchiro** [comment]
Yeah, that would be an option.
If we do that, though, we should drop the current support for the `plugin` configuration option, as it'd be redundant.

**Comment by tbm** [comment]
Agreed.

So should I implement that or do you have a better idea?

**Comment by zacchiro** [comment]
I'm fine with adding an option to specify a generic header file that should be inlined in the output to cope with current Beancount limitations.

**Comment by tbm** [comment]
Do you think we should remove `operating_currencies` from the config file since people can put that in the header or should I leave it there?

**Comment by zacchiro** [comment]
Yeah... good question. The generic mechanism is appealing for everything, I guess. But OTOH forcing people to create an extra file to be inlined for very commonly used options is awkward. Is my understanding that `operating_currencies` basically *always* needed correct? If so, I think it warrants special casing. If not, we can drop it.

**Comment by tbm** [comment]
I'm not sure it's needed for beancount itself but fava needs it. Anyway, since it's there already, let's leave it there.
