### ISSUE TITLE
document how to install on Windows

### ISSUE THREAD

**Issue by gety9** [zacchiro/ledger2beancount#101]
Guys hi,

How ledger2beancount can be installed on Windows?
Installation manual provides directions for Debian, but not for Windows users.

**Comment by tbm** [comment]
I don't use Windows so I can't answer this question.

But if there's a way to install the Perl modules on Windows, the script may work.

http://www.cpan.org/modules/INSTALL.html mentions Strawberry Perl which includes cpanm and then you can use that to install the modules.

**Comment by tbm** [comment]
@gety9 did you get a chance to try Strawberry Perl?

**Comment by tbm** [comment]
@gety9 can you install Strawberry Perl on Windows so we can document how to use ledger2beancount on Windows?

**Comment by gety9** [comment]
@tbm 

Martin hi, 

Nope, import file/data was very small so i did it manually.

**Comment by tbm** [comment]
I tested ledger2beancount with [Strawberry Perl](http://strawberryperl.com/) on Windows and it works.
