### ISSUE TITLE
Use or remove Carp::Assert

### ISSUE THREAD

**Issue by tbm** [zacchiro/ledger2beancount#104]
After all the refactoring, we're now actually using `Carp::Assert` anymore.  Should I remove it or do you think it makes sense to add some `assert` statements (and if so, where)?

**Comment by zacchiro** [comment]
I like assertions, but it's not like we're gonna add them around just to keep Carp::Assert :)
OTOH, I'm not sure it's worth flip-flopping with it (in the code, the doc, etc.). I'm for just keeping it around even if it is unused. Tentatively closing this on that basis, feel free to reopen if you disagree.
