### ISSUE TITLE
add the ability to selectively ignore input lines

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/ledger2beancount#110]
While ledger2beancount can translate most ledger directives to equivalent beancount ones, it is sometime desirable to selectively ignore input lines. For instance, specific `include` directives (but not others) in a Ledger setup might be unneeded in the resulting beancount setup.

To support this I propose to replicate a mechanism that is popular for linting tools: support inline comments that tell the tool to look away, e.g.:
```
include foo.ledger
include bar.ledger  ; NoL2B
include baz.ledger
```
will be translated to:
```
include "foo.beancount"
include "baz.beancount"
```

To be fully generic this will also need a block-level equivalent, e.g.
```
; NoL2B_begin
stuff in between these two will be completely
; NoL2B_end
```
but that is not strictly needed to make an initial version of this feature useful.

**Comment by zacchiro** [comment]
On Sun, Apr 15, 2018 at 09:18:30PM +0000, Martin Michlmayr wrote:
> Yeah, I'm just wondering about the syntax. Is `NoL2B` what we should use?

Well, that was just a first proposal.
Feel free to propose something else.

**Comment by tbm** [comment]
I don't have a better idea. Maybe we should let users define a tag in the config file and then we look for `; $TAG` and `$TAG begin` or something.  This way we can avoid the question of how to name the tag. ;)

**Comment by zacchiro** [comment]
On Mon, Apr 16, 2018 at 10:33:01AM +0000, Martin Michlmayr wrote:
> I don't have a better idea. Maybe we should let users define a tag in
> the config file and then we look for `; $TAG` and `$TAG begin` or
> something.  This way we can avoid the question of how to name the
> tag. ;)

let's not overdo this :)

**Comment by tbm** [comment]
> let's not overdo this :)

I thought about it some more and there are actually good reasons for having a config variable for the tag:

1) Users can set it to `''` or unset it (maybe you want the ignore in one config but not another). We probably need an option to turn on these ignores anyway and this way I don't need to come up with a name for the config variable (I'd probably come up with something stupid like `ignore_ignore`)

2) It would allow you to define different tags in different configs, so you could device to ignore some stuff in one case and other stuff in another case.  I'm not sure there's actually any need for it, but we get it for free anyway.

I'll propose a PR.

**Comment by zacchiro** [comment]
done by @tbm in df7dcb08d4cf7406d13e9f94fb866ab5df97a0f2
