### ISSUE TITLE
chokes on transactions without description

### ISSUE THREAD

**Issue by jelmer** [zacchiro/ledger2beancount#123]
ledger seems happy with this transaction in my ledger file:

     2005/02/08
         Expenses:Books                         EUR 60.42
         Assets:Current Assets:ING:Checking Account

but ledger2beancount chokes on it:
Cannot process transaction header: 2005/02/08

Adding some spaces to the end of the date works around the issue.

**Comment by tbm** [comment]
Thanks for the report, Jelmer. You're right. Additionally, no whitespace is required between flag, code and narration.

I've opened PR #124 if you want to try the fix.
