### ISSUE TITLE
use "note" for account notes instead of "description"?

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/ledger2beancount#126]
ledger allow note entries associated to accounts (and maybe other directives? I haven't checked), like this:

    account Expenses:Membership
        note organization membership, non-profits, political parties, etc.

ledger2beancount currently ignores note entries.

We should support them somewhat, at least to avoid losing information. For instance, we can convert them to line-long comments.

**Comment by aumayr** [comment]
There is a `note` directive in Beancount, but there is a explicit date attached. The example given would look like this:

```ruby
2018-05-23 note Expenses:Membership "organization membership, non-profits, political parties, etc."
```

Another possibility would be to add it to the `open` statement of an account, eg.

```ruby
2018-05-23 open Expenses:Membership
   note: "organization membership, non-profits, political parties, etc."
```

**Comment by tbm** [comment]
> ledger2beancount currently ignores note entries.

It shouldn't.  A "note" is converted to "description" metadata for accounts and for commodities you get metadata "name" for a note.

```
1970-01-01 open Expenses:Membership
    description: "organization membership, non-profits, political parties, etc."
```

Does this not happen for you?

Since beancount apparently supports `note` metadata I guess we should use that. @aumayr does that exist for commodities too?

**Comment by zacchiro** [comment]
My bad, I was looking at an outdated beancount file after having modified the source ledger one. I do have `description` metadata for accounts, as expected.

**Comment by tbm** [comment]
I think we should reopen this as @aumayr had some good input.  If "note" is more official in beancount than "description" we should use that instead.

@aumayr can you clarify on this point (and my question regarding commodities)?

**Comment by zacchiro** [comment]
On Thu, May 24, 2018 at 02:32:14AM -0700, Martin Michlmayr wrote:
> I think we should reopen this as @aumayr had some good input.  If
> "note" is more official in beancount than "description" we should use
> that instead.

Sure, feel free to reopen/retitle as needed.

**Comment by tbm** [comment]
@aumayr can you provide more input on this?

**Comment by aumayr** [comment]
> Since beancount apparently supports note metadata I guess we should use that. @aumayr does that exist for commodities too?

In fact, it does:

```ruby
# Straight from the Beancount docs: https://docs.google.com/document/d/1wAMVrKIA2qtRGmoVDSUBJGmYZSygUaR0uOMW1GV3YE0/edit

2012-01-01 commodity HOOL
  name: "Hooli Corporation Class C Shares"
  asset-class: "stock"
```

**Comment by tbm** [comment]
> In fact, it does:

@aumayr sorry, I think I wasn't clear.  I understand that accounts and commodities support meta-data but afaik the meta-data has no pre-defined meaning, so you can use whatever keys you want.

I understood your original comment to mean that the key `note` has a special in beancount and I wanted to clarify if it indeed does.  But I cannot find anything about `note` being special so I guess it makes little different if we use `note` or `description`.

**Comment by tbm** [comment]
I'm closing this.  I find no evidence that `note` or `name` or whatever has any special meaning
