### ISSUE TITLE
fails to detect posting tags in inline comments

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/ledger2beancount#127]
Example:

    2018-05-19 * "pool"
      Expenses:Entertainement:Pool                4.00 EUR  ; mum
      Expenses:Entertainement:Pool                2.50 EUR  ; :kid:
      Expenses:Cash

The above should behave the same of:

    2018-05-19 * "pool"
      Expenses:Entertainement:Pool                4.00 EUR  ; mum
      Expenses:Entertainement:Pool                2.50 EUR
        ; :kid:
      Expenses:Cash

but it currently doesn't. In the latter case `kid` is properly recognized as a tag (and hence converted to a fake `tags:""` metadata key, because Beancount doesn't yet support posting tags, but that's another story…). In the former case the in-line comment `; :kid:` is preserved as is in the generated Beancount.

**Comment by tbm** [comment]
It seems we handle metadata on the same line but not tags.
