### ISSUE TITLE
cpanm installation fails

### ISSUE THREAD

**Issue by RidaAyed** [zacchiro/ledger2beancount#131]
Hi

TLDR: How can I install ledger2beancount?

Longer version: What step did I miss in installing ledger2beancount?

Following this line 
> cpanm --installdeps .

in installation guide, I execute:

`~ cpanm --installdeps . --sudo`

and receive the message below:

```sh
--> Working on .
Configuring /home/ra ... N/A
! Configuring . failed. See /home/ra/.cpanm/work/1532616976.4673/build.log for details.
```

The log message 
`~ cat /home/ra/.cpanm/work/1532616976.4673/build.log for details.`

reveals:
```txt
cpanm (App::cpanminus) 1.7044 on perl 5.026002 built for x86_64-linux-thread-multi
Work directory is /home/ra/.cpanm/work/1532616373.23722
You have make /usr/bin/make
You have LWP 6.33
You have /usr/bin/tar: tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
!
! Can't write to /usr/share/perl5/site_perl and /usr/bin: Installing modules to /home/ra/perl5
! To turn off this warning, you have to do one of the following:
!   - run me as a root or with --sudo option (to install to /usr/share/perl5/site_perl and /usr/bin)
!   - Configure local::lib in your existing shell to set PERL_MM_OPT etc.
!   - Install local::lib by running the following commands
!
!         cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
!
--> Working on .
Entering /home/ra/bin
Configuring /home/ra/bin
-> N/A
! Configuring . failed. See /home/ra/.cpanm/work/1532616976.4673/build.log for details.
Expiring 2 work directories.
```

Following the log file's hints and executing this line does not help either:
`cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)`

---
OS: *Arch Linux 4.17.9*  
ledger2beancount AUR Installation status: #130

**Comment by tbm** [comment]
Hmm:

> Can't write to /usr/share/perl5/site_perl and /usr/bin: Installing modules to /home/ra/perl5

Which is weird because you're passing `--sudo`.  What happens if you use `cpanm --sudo --installdeps .` instead of `cpanm --installdeps . --sudo`?

I don't know but this sounds more like a cpanm usage issue.  The dependency file itself should be up to date.

**Comment by RidaAyed** [comment]
Thank you for having a look Martin @tbm 

Tried your suggestion as

`cd ~`
`cpanm --sudo --installdeps .`

```
--> Working on .
Configuring /home/ra ... N/A
! Configuring . failed. See /home/ra/.cpanm/work/1532680018.20391/build.log for details.
```

`cat /home/ra/.cpanm/work/1532680018.20391/build.log`

```
cpanm (App::cpanminus) 1.7044 on perl 5.026002 built for x86_64-linux-thread-multi
Work directory is /home/ra/.cpanm/work/1532680018.20391
You have make /usr/bin/make
You have LWP 6.33
You have /usr/bin/tar: tar (GNU tar) 1.30
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.
You have /usr/bin/unzip
--> Working on .
Entering /home/ra
Configuring /home/ra
-> N/A
! Configuring . failed. See /home/ra/.cpanm/work/1532680018.20391/build.log for details.
```

**Comment by tbm** [comment]
Did you try without `--sudo`?  This installs in `~/perl5` and works for me.

BTW, the docs don't mention `--sudo`

**Comment by tbm** [comment]
I think I'm going to close this issue since it works for me.

@RidaAyed did you try `cpanm` without `--sudo`? This works for me.

**Comment by tbm** [comment]
@RidaAyed I'm about to close this ticket since it works for me. Can you try `cpanm` without `--sudo`?

**Comment by tbm** [comment]
Closing as it works for me as documented.
