### ISSUE TITLE
support beancount-only sections in input ledger

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/ledger2beancount#132]
Similarly to the current support offered by `NoL2B begin`/`NoL2B end` to _exclude_ Ledger-CLI sections from `ledger2beancount` processing, it would be nice to have the ability to support Beancount-only sections in the input Ledger-CLI file.

A concrete use case of mine is interspersing Beancount event directives into my ledger.

To support this we can add two markers, e.g., `L2Bonly begin`/`L2Bonly end`, and require that all content in between them is commented with `;`, as it will not necessarily be Ledger-valid syntax. `ledger2beancount` will strip the markers, uncomment the lines in between, and emit them unmodified in Beancount output.

**Comment by tbm** [comment]
Seems very specific to me and not fully in line with the whole ledger to beancount idea, but I'm ok with adding it to make you happy :)

**Comment by zacchiro** [comment]
oh, no, I don't want to force a specific use case of mine :-)

I'm curious as to why you consider it very specific too. My view here is that `ledger2beancount` has become a tool (it _probably_ wasn't the case in the beginning, but it certainly is now) that allow to use a Ledger-CLI input ledger as the master document to maintain a Beancount ledger. In a sense, I'm thinking of it now as a _frontend_ to Beancount, rather than just a _migration_ tool. Does that make sense? And do you agree?

_If_ this view is correct, than I think this feature makes sense. It probably doesn't if you hold only the fire-and-forget-migration-tool view.

**Comment by tbm** [comment]
Yeah, I tend to agree with that view. I think it's been shown to be useful to use both ledger and beancount and the tools helps with that.

**Comment by zacchiro** [comment]
OK. And, according to that view, do you still see this feature request as too specific? Because if we allow to use Ledger as a front-end to Beancount, I see no other obvious way of supporting Beancount-only features within a Ledger file.

**Comment by tbm** [comment]
Yeah, you're right. The tool has evolved.

**Comment by tbm** [comment]
I'm just about to implement this.  Do you have any example?  I need a good example for the docs.

**Comment by zacchiro** [comment]
On Tue, Sep 04, 2018 at 04:43:35AM -0700, Martin Michlmayr wrote:
> I'm just about to implement this.  Do you have any example?  I need a
> good example for the docs.

I think we can use examples from the Beancount documentation about
directives that are not supported by Ledger. Here are a few:

    2013-11-03 note Liabilities:CreditCard "Called about fraudulent card."

    2014-07-09 event "location" "Paris, France"
    2018-09-01 event "location" "Bologna, Italy"

    2014-07-09 query "france-balances" "
      SELECT account, sum(position) WHERE ‘trip-france-2014’ in tags"

    ; Closing credit card after fraud was detected.
    2016-11-28 close Liabilities:CreditCard:CapitalOne 

TIA

**Comment by tbm** [comment]
This is indeed useful.
