### ISSUE TITLE
Assign metadata based on account name

### ISSUE THREAD

**Issue by tbm** [zacchiro/ledger2beancount#138]
I'm not sure if this feature should actually be in ledger2beancount since it doesn't have anything to do with the necessary conversion.  Basically, I'd like to assign metadata based on account names.

e.g. define this (probably with a better name for the variable)
```
metadata_match_account:
  - project: ^Income:(?<value>[^:]+)
  - donation: ^Income:.*:Donation
```

and given the input

```
    Income:Foo:Donations         -8.00 EUR
    Income:Bar:Donations        -12.00 EUR
```
I'd get:
```2018-09-28 * "Test"
  Assets:Bank                  20.00 EUR
  Income:Foo:Donations         -8.00 EUR
    project: "Foo"
    tags: "donation"
  Income:Bar:Donations        -12.00 EUR
    project: "Bar"
    tags: "donation"

```

While this is useful, I'm not sure if it should be in ledger2beancount or not since you could simply add that metadata to the input ledger file with some Perl code.  What do you think?

**Comment by zacchiro** [comment]
On Fri, Sep 28, 2018 at 12:11:33PM -0700, Martin Michlmayr wrote:
> I'm not sure if this feature should actually be in ledger2beancount
> since it doesn't have anything to do with the necessary conversion.
> Basically, I'd like to assign metadata based on account names.

Yeah, I don't think that belongs to ledger2beancount. One reason is the
one you mentioned --- it doesn't have anything to do with the
conversion, and I think we should resist feature creep. Another reason
is that in Beancount there is a much better way to implement this: write
a plugin that adds the metadata you want.

So, nack from me on this.

**Comment by tbm** [comment]
> Another reason is that in Beancount there is a much better way to implement this: write a plugin that adds the metadata you want.

That won't work in this case but thanks for confirming my doubts about adding the feature.
