### ISSUE TITLE
Spacing between account and amount is not correctly identified

### ISSUE THREAD

**Issue by Joradi98** [zacchiro/ledger2beancount#163]
The ledger file 

```
2016-11-01 Food
	Assets:Money 	 -35.00 EUR
	Expenses:Food	 35.00 EUR
```

is converted to

```
2016-11-01 txn "Food"
  -35.00 ASSETS-MONEY EUR
  35.00 EXPENSES-FOOD EUR
```

The problem is caused by an irregular spacing between the account name and the amount. 
`Assets:Money(whitespace)(TAB)(whitespace)-35.00 EUR` is valid in ledger, but confuses the converter.

Replacing the tabular character with whitespaces resolved the issue for me. Nevertheless, I wanted to document this behavior.

**Comment by tbm** [comment]
Thanks, this is definitely a bug.

**Comment by tbm** [comment]
Thanks for reporting this issue.  Please open more issues if you ran into other problems.

**Comment by Joradi98** [comment]
Wow, that was fast. Thank you very much!
