### ISSUE TITLE
Account "Income" results in invalid bean count syntax

### ISSUE THREAD

**Issue by Joradi98** [zacchiro/ledger2beancount#164]
Using the account name "Income" results in invalid bean count syntax.

The ledger file
```
2016-11-01 Salary
	Assets:Money 	 42.00 EUR
	Income
```
is converted to
```
1970-01-01 open Assets:Money
1970-01-01 open Income
1970-01-01 commodity EUR
2016-11-01 txn "Salary"
  Assets:Money 	 42.00 EUR
  Income
```

which does not pass bean-check.
I am new to beancount, but Income seems to be a reserved keyword. It can be fixed using the `account_map` entry in the configuration file though 👍

**Comment by tbm** [comment]
> I am new to beancount, but Income seems to be a reserved keyword. It can be fixed using the account_map entry in the configuration file though

Yes, beancount requires certain top-level keywords unless you change them.

While `Income` is a valid top-level keyword, it seems `Income` by itself is not permitted. It has to be `Income:something`.

ledger2beancount can't fix all issues that will be flagged by bean-check.  I think this is sufficiently documented in the documentation, but I guess I could special case `Income` to be changes to `Income:FIXME` or something.  I don't know if that makes sense.

**Comment by tbm** [comment]
Ok, I thought about this. I'll make two changes to improve the current situation. Thanks again for your feedback.

**Comment by tbm** [comment]
First, we'll rename `Income` to `Income:Subaccount` and add the following conversion note:

```
;   - Income not allowed; it needs a subaccount, e.g. Income:Subaccount
;   - Account Income renamed to Income:Subaccount
```

**Comment by tbm** [comment]
Second, if a non-standard root name is used (e.g. Capital instead of Equity), we add this warning:
```
;   - Non-standard root Capital used; please set name_* option
```

**Comment by tbm** [comment]
And third I updated the docs to mention the beancount `name_*` options for non-standard root names.

2 and 3 are not directly related to your issue, but came to my mind as I was thinking about root names. thanks.
