### ISSUE TITLE
Rewrite -*- ledger -*- emacs tag

### ISSUE THREAD

**Issue by tbm** [zacchiro/ledger2beancount#165]
We should probably change the emacs ledger tag

    ; -*- ledger -*-

Unfortunately I'm not quite sure to what since it might depend on whether beancount in emacs is a minor or major mode, whatever that even means.

**Comment by tbm** [comment]
bean-extract generates:

```
;; -*- mode: beancount -*-
```

But from what I understand, it depends on whether beancount in Emacs is a minor or major mode. I don't know what that means.

@zacchiro do you know what the right identified is?  I'd like to finally resolve this issue.

**Comment by zacchiro** [comment]
On Sat, Feb 15, 2020 at 12:38:07AM -0800, Martin Michlmayr wrote:
> ```
> ;; -*- mode: beancount -*-
> ```
> 
> But from what I understand, it depends on whether beancount in Emacs is a minor or major mode. I don't know what that means.
> 
> @zacchiro do you know what the right identified is?  I'd like to finally resolve this issue.

beancount-mode is now a major mode upstream.
The above is correct, you can use that syntax.

**Comment by tbm** [comment]
thanks. What's the official name of this thing. Is it a tag? A marker? Just for the changelog.

**Comment by zacchiro** [comment]
On Sun, Feb 16, 2020 at 02:26:37AM -0800, Martin Michlmayr wrote:
> thanks. What's the official name of this thing. Is it a tag? A marker? Just for the changelog.

It's called a "modeline".

Thanks for fixing this!
