### ISSUE TITLE
double root account name after using account regex

### ISSUE THREAD

**Issue by MisterY** [zacchiro/ledger2beancount#176]
I'm using the following definition:
```
account_regex:
  ^Trading:(.*): Equity:Trading:$1
```
and it applies correctly for the "open" directive:
```
1970-01-01 open Equity:Trading:CURRENCY:AUD
```
while there is an extra "Equity" in the journal!
```
2017-10-06 txn ""
  Assets:Investments:Broker:Cash--EUR-        5.71 EUR @@ 6.71 USD
  Equity:Equity:Trading:CURRENCY:USD                     6.71 USD
  Assets:Investments:Broker:Cash--USD-       -6.71 USD
  Equity:Equity:Trading:CURRENCY:EUR                    -5.71 EUR @@ 6.71 USD
```
These are then reported as invalid transactions.

**Comment by MisterY** [comment]
This is a follow up on the discussion thread in the group.
I have a file exported from Gnucash and it is using Trading accounts in the root, which I want to move under equity in the bean file.

**Comment by tbm** [comment]
Oh, thanks for much for reporting this issue.  This is a really interesting bug.

**Comment by tbm** [comment]
This bug isn't actually related to account_regex, which is why it took me a while to track down.

This bug has been there for quite some time, so thanks for finding it.

**Comment by MisterY** [comment]
Happy to help out as much as I can.
