### ISSUE TITLE
Lot costs not converted

### ISSUE THREAD

**Issue by fdw** [zacchiro/ledger2beancount#180]
I track my expenses in hleder like this:
```
2020/01/11 Sample transaction
  assets:depot    2 GOOG @@ 1000 EUR
  assets:cash      -1000 EUR
```

However, the cost is lost on conversion, leaving me with an unbalanced:
```
2020-01-11 txn "Sample transaction"
  Assets:Depot  2 GOOG
  Assets:Cash  -1000 EUR
```

If I understand the syntax correctly, the second line should be `Assets:Depot  2 GOOG {{1000 EUR}}`, right?

**Comment by tbm** [comment]
> If I understand the syntax correctly, the second line should be Assets:Depot 2 GOOG {{1000 EUR}}, right?

It should either be `Assets:Depot   2 GOOG {{1000 EUR}}` or `Assets:Depot   2 GOOG @@ 1000 EUR` depending on what `GOOG` is (see section `Lots` in the manual), but yeah, in this case it should be the former.

And that's when I get when I run ledger2beancount, so not sure why this is not working for you.

What's your config file?  I don't see how a config option could lead to this invalid file, but who knows.

I assume you're using the latest version from Git?

**Comment by fdw** [comment]
Thanks to your ideas, I tested some more, and found my stupid error: I forgot the currency in the original ledger file (so it was `Assets:Depot  2 GOOG @@ 1000`), which is completely ignored by `ledger2beancount`.

Thanks for your help and this tool, and sorry to have wasted your time.

**Comment by tbm** [comment]
Thanks for your feedback @fdw. It seems you just made an error.

Amounts without commodities are actually allowed in ledger (although not recommended), so it makes sense to add a note about this in the docs.
