### ISSUE TITLE
Detection of account name is not correct

### ISSUE THREAD

**Issue by thdox** [zacchiro/ledger2beancount#185]
With this input file

```
2018/03/26 * John Doe
    Actif:Remboursement:John  ; [=2017/10/04] Abonnement Théâtre
    Actif:Courant:BnpCc                      85,00 €
```
I get 
```
;----------------------------------------------------------------------
; ledger2beancount conversion notes:
;
;   - Account Actif:Remboursement:John Abonnement Théâtre renamed to Assets:Remboursement:John-Abonnement-Théâtre
```
I know that aux_date is to be ignored, and I would have expected that the below account is correctly detected. 

Actif:Remboursement:John

**Comment by tbm** [comment]
Thanks, Thierry!  That's definitely a bug.

**Comment by tbm** [comment]
Some parts of ledger2beancount are a bit ugly. This is one of them. ;)

I have a fix. I'll test some more tomorrow and commit. Thanks again.
