### ISSUE TITLE
no longer convert per-posting comments to comment metadata

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/ledger2beancount#21]
after merging #18 , and with `tag_as_metadata: true` (in case that matters), I no longer have "comment: ..." metadata, that were used to capture per-posting comments (that are not supported by Beancount ATM)

**Comment by zacchiro** [comment]
(yes, this should have had, and should still have, a regression test associated)

**Comment by tbm** [comment]
I can't reproduce this.

```

2018-03-17 * Test
    ; :tag:
    ; Another comment
    Assets:Test                        10.00 EUR ; What an "interesting" accout name
    ; see beancount issue #143
    Equity:Opening-Balance            -10.00 EUR ; Opening balance?
      ; posting comment
```

gives me:

```
2018-03-17 * "Test"
  tags: "tag"
  comment: "Another comment"
  Assets:Test                        10.00 EUR ; What an "interesting" accout name
  comment: "see beancount issue #143"
  Equity:Opening-Balance            -10.00 EUR ; Opening balance?
    comment: "posting comment"
```

Do you have an example?

**Comment by tbm** [comment]
I wonder if the bug is caused by the aux-date on posting-level change.

**Comment by tbm** [comment]
This was broken by 16e44b4c5 as you said. Hmm
