### ISSUE TITLE
provide sane defaults for configuration file options

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/ledger2beancount#38]
Currently most configuration file options are mandatory: they should be specified even if unused, because no default at all is provided in ledger2beancount. We should fix this.

Note that there are two use cases served by defaults:
- provide sane defaults, when no customization is needed, reducing the size/complexity of configuration file
- provide sane upgrade paths: when we add an option to ledger2beancount, users should not be forced to change their configuration (unless it's a major semantics change, of course)

**Comment by tbm** [comment]
Yes, that definitely makes sense.
