### ISSUE TITLE
Assertion failed when date_match doesn't match date

### ISSUE THREAD

**Issue by tbm** [zacchiro/ledger2beancount#40]
With a regex in `date_match` that doesn't match the date in the ledger file I get:

```
2018-03-19 * Test
Assertion failed!
 at /usr/share/perl5/Carp/Assert.pm line 282, <> line 3.
	Carp::Assert::assert(0) called at ./bin/ledger2beancount-txns line 454
```

**Comment by zacchiro** [comment]
ok, but what should be the expected behavior here?
i'd say a properly formatted error, but still we should abort processing, do you agree?

**Comment by tbm** [comment]
The [ledger manual](https://www.ledger-cli.org/3.0/doc/ledger3.html#Transactions-and-Comments) says

> A line beginning with a number denotes a transaction

**Comment by tbm** [comment]
>  i'd say a properly formatted error, but still we should abort processing, do you agree?

Yes, definitely.
