### ISSUE TITLE
offer ability to treat payee_match (et al) case insensitive

### ISSUE THREAD

**Issue by tbm** [zacchiro/ledger2beancount#50]
payee_match (et al) should be case insensitive. Plus update docs.

**Comment by zacchiro** [comment]
Why should it be case insensitive?
I'm not necessarily opposed, but I'd like to understand the use case.
I can see situations in which users would want the matching to be case-insensitive, as well as others where the converse is true.
So I think ideally we should allow user to specify case sensitive/insensitive in their regexp.

Is the fact that it is complicated to allow users to do that (due to the way Perl `//` syntax work) the real problem here?

**Comment by tbm** [comment]
> I'm not necessarily opposed, but I'd like to understand the use case.

My example is that I was matching on "Annual fee" but realized I should also match on lower case.  But yeah, I could probably update my match.

Unfortunately I don't know how users could specify that.  We only put the actual regex in the config file, not the whole /.../i match.  And I don't even think that's possible.  Maybe you have ideas?

I also noticed that not all patterns are allowed, e.g. .* is fine but \d not.  It's probably escaped.  We should probably document that but again I don't know the exact rules.

**Comment by zacchiro** [comment]
> Unfortunately I don't know how users could specify that. We only put the actual regex in the config file, not the whole /.../i match. And I don't even think that's possible. Maybe you have ideas?

Not out of the box (yet), but this is precisely the syntax problem I was referring to. Need to be investigated more.

> I also noticed that not all patterns are allowed, e.g. .* is fine but \d not. It's probably escaped. We should probably document that but again I don't know the exact rules.

That's bad, as it means we're not saying the true when we point people to perl regexs as what they can use. We can fix the doc, but I'd rather fix the underlying problem and allow people to use `\d` :-) This deserves a dedicated issue I think.

**Comment by tbm** [comment]
I don't know how. Maybe you can investigate.

**Comment by zacchiro** [comment]
Yeah, but I need an example where `\d` doesn't work. From what I can see we already use `\d` in other regexs, and it works just fine.

**Comment by tbm** [comment]
Hmm maybe it was something else. Let me investigate...

**Comment by tbm** [comment]
The problem wasn't the `\d`. I have a fix.

But can you think about a way to allow users whether they want case sensitivity or not.

**Comment by olasd** [comment]
If you want case-insensitivity, can't you just prefix your configured pattern with `(?i)`? (http://perldoc.perl.org/perlre.html#Extended-Patterns)

**Comment by tbm** [comment]
@olasd thanks, Nicolas! I have never heard of this feature before.  I just confirmed that it works as expected.

I'll update the docs tomorrow.

**Comment by zacchiro** [comment]
What I wasn't sure is if one could use the case insensitive regex flag that @olasd mentioned from the config file and interpret it as such. It clearly forks with the usual regex quote mechanism, as your example in the doc now shows, so yay! :)
Thanks to both of you.
