### ISSUE TITLE
emit missing account definitions

### ISSUE THREAD

**Issue by tbm** [zacchiro/ledger2beancount#55]
ledger allows you to define accounts but it's optional whereas it's required in beancount. ledger2beancount should create a list of accounts in use and declare them.

**Comment by zacchiro** [comment]
Agreed. Although the expected semantics is not entirely clear to me. There might be some accounts declared in ledger (which are currently handled by ledger2beancount-accounts), and some which are not. Proposal:
- always convert the explicitly declared accounts
- have a boolean option (default to false) that determines whether ledger2beancount should *additionally* emit declaration of used-but-not-declared accounts

**Comment by tbm** [comment]
What's your reason to make the second step optional?

I'd convert the ledger definition to beancount, and automatically create definitions for any remaining accounts.

I mean, I can add an option.  But I think I'd prefer to just generate a valid beancount file by default and let people edit later to adjust.

**Comment by zacchiro** [comment]
Oh, my bad, you're right, Beancount *requires* account declaration, so it would not be sane behavior not to emit them. So, semantics is easy here, YAY :)
