### ISSUE TITLE
add option to specify non default configuration file

### ISSUE THREAD

**Issue by zacchiro** [zacchiro/ledger2beancount#63]
use case:
```
ledger2beancount -c l2b-accounts.yml < accounts.ledger > accounts.beancount
ledger2beancount -c l2b-transactions.yml < current.ledger > current.beancount
ledger2beancount -c l2b-prices.yml < pricedb.ledger > pricedb.beancount
```
proposed syntax:
- getopt with both `-c` and `--conf`
proposed semantics:
- if -c/--conf is given, it *replaces* the default places where `ledger2beancount.yml` is looked for, ignoring it, and using the given conf file instead

**Comment by tbm** [comment]
I used `--config` instead of the `--conf` you suggested, but if `--conf` is more common please change when you merge the PR.
