### ISSUE TITLE
Handle commodities with umlauts/UTF-8

### ISSUE THREAD

**Issue by tbm** [zacchiro/ledger2beancount#67]
ledger:

```
2016-04-28 * Commodity with umlaut
  Assets:Test                       1.00 Föo
Equity:Opening balance
```

The commodity is not mapped, even though I have a mapping defined.

**Comment by zacchiro** [comment]
yeah, our regexs for "letters" should use character classes (which hopefully are unicode-aware) rather than `a-z` everywhere
