### ISSUE TITLE
non-indented block comments lead to Assertion failed (Carp::Assert::assert("") called at ... line 755)

### ISSUE THREAD

**Issue by gour** [zacchiro/ledger2beancount#98]
Hello,

I'm trying to convert my hledger file into beancount, but get the following:
```
$ledger2beancount personal.ledger > personal.beancount
Assertion failed!
 at /usr/share/perl5/vendor_perl/Carp/Assert.pm line 282.
	Carp::Assert::assert("") called at /home/gour/bin/ledger2beancount line 755
```

so wonder if you have any tip what might be wrong since, based on `line 755` it does not look as the date-parsing problem?

**Comment by tbm** [comment]
hledger isn't really supported at the moment since the file format is slightly different to ledger.

Line 755 refers to the assert statement in the Perl script. Looking at the code, it seems this assert is about an `end` after a `comment`, e.g.

```
comment
  This is a comment
  More comment
end
```
Does that make sense?  Does personal.ledger not have an `end` after the comment? Is this not required in hledger?

**Comment by tbm** [comment]
So I looked the test suite from ledger itself and noticed this:

```
comment
foo bar
end comment
```

Whereas ledger2beancount expects comments to be indented by whitespace.  But it seems that's not requirement.

Can you confirm this describes the issues you're seeing?

**Comment by gour** [comment]
> Can you confirm this describes the issues you're seeing?

That was it - I had comment block for the price database and after commenting it, conversion went well, except that now I have to fix account names etc.

**Comment by tbm** [comment]
Ok, great!  @gour if you find anything where you think the conversion could have been better when you look at the generated beancount file, please open a new issue.

**Comment by tbm** [comment]
btw, I opened a PR with a fix for the issue you saw.  Maybe you can test it later.

**Comment by gour** [comment]
> if you find anything where you think the conversion could have been better when you look at the generated beancount file, please open a new issue.

Sure. :smiley: 

> btw, I opened a PR with a fix for the issue you saw. Maybe you can test it later.

I've just tried it and it works. :+1:
